[default]
timeout = 120
waitUntil = "domcontentloaded"
waitForSelector = "pre"

[Archive]
title = "New Album Releases - Archive"
url = "https://r.jina.ai/http://newalbumreleases.net/category/cat/"
entrySelector = "pre"
titleSelector = "pre"
contentSelector = "pre"
