[default]
timeout = 60
waitUntil = "networkidle"

[Archive]
title = "New Album Releases - Archive"
url = "https://r.jina.ai/http://newalbumreleases.net/category/cat/"
entrySelector = "body"
titleSelector = "title"
linkSelector = "a"
contentSelector = "body"
